/// <reference types="./src/types" />
import { SConst } from "./SConst";
export declare abstract class Constants extends SConst {
    static readonly SIYUAN_ORIGIN_VERSION: string;
    static readonly SIYUAN_VERSION: string;
    static readonly NODE_ENV: string;
    static readonly SIYUAN_APPID: string;
    static readonly ASSETS_ADDRESS: string;
    static readonly PROTYLE_CDN: string;
    static readonly UPLOAD_ADDRESS: string;
    static readonly SIYUAN_DROP_FILE: string;
    static readonly SIYUAN_DROP_GUTTER: string;
    static readonly SIYUAN_DROP_TAB: string;
    static readonly SIYUAN_DROP_EDITOR: string;
    static readonly SIYUAN_SHOW: string;
    static readonly SIYUAN_CONFIG_TRAY: string;
    static readonly SIYUAN_OPEN_WORKSPACE: string;
    static readonly SIYUAN_QUIT: string;
    static readonly SIYUAN_HOTKEY: string;
    static readonly SIYUAN_INIT: string;
    static readonly SIYUAN_OPENURL: string;
    static readonly SIYUAN_OPENWINDOW: string;
    static readonly SIYUAN_SEND_WINDOWS: string;
    static readonly SIYUAN_SAVE_CLOSE: string;
    static readonly SIYUAN_EXPORT_PDF: string;
    static readonly SIYUAN_EXPORT_CLOSE: string;
    static readonly SIYUAN_EXPORT_PREVENT: string;
    static readonly SIZE_TOOLBAR_HEIGHT: number;
    static readonly SIZE_GET_MAX = 102400;
    static readonly SIZE_UNDO = 64;
    static readonly SIZE_TITLE = 512;
    static readonly SIZE_EDITOR_WIDTH = 760;
    static readonly SIZE_ZOOM: number[];
    static readonly CB_MOUNT_HELP = "cb-mount-help";
    static readonly CB_MOUNT_REMOVE = "cb-mount-remove";
    static readonly CB_GET_APPEND = "cb-get-append";
    static readonly CB_GET_BEFORE = "cb-get-before";
    static readonly CB_GET_UNCHANGEID = "cb-get-unchangeid";
    static readonly CB_GET_HL = "cb-get-hl";
    static readonly CB_GET_FOCUS = "cb-get-focus";
    static readonly CB_GET_FOCUSFIRST = "cb-get-focusfirst";
    static readonly CB_GET_SETID = "cb-get-setid";
    static readonly CB_GET_ALL = "cb-get-all";
    static readonly CB_GET_BACKLINK = "cb-get-backlink";
    static readonly CB_GET_UNUNDO = "cb-get-unundo";
    static readonly CB_GET_SCROLL = "cb-get-scroll";
    static readonly CB_GET_CONTEXT = "cb-get-context";
    static readonly CB_GET_HTML = "cb-get-html";
    static readonly CB_GET_HISTORY = "cb-get-history";
    static readonly LOCAL_ZOOM = "local-zoom";
    static readonly LOCAL_SEARCHEDATA = "local-searchedata";
    static readonly LOCAL_SEARCHEKEYS = "local-searchekeys";
    static readonly LOCAL_DOCINFO = "local-docinfo";
    static readonly LOCAL_SEARCHEKEY = "local-searchkey";
    static readonly LOCAL_DAILYNOTEID = "local-dailynoteid";
    static readonly LOCAL_HISTORYNOTEID = "local-historynoteid";
    static readonly LOCAL_CODELANG = "local-codelang";
    static readonly LOCAL_FONTSTYLES = "local-fontstyles";
    static readonly LOCAL_EXPORTPDF = "local-exportpdf";
    static readonly LOCAL_EXPORTWORD = "local-exportword";
    static readonly LOCAL_EXPORTIMG = "local-exportimg";
    static readonly LOCAL_BAZAAR = "local-bazaar";
    static readonly LOCAL_PDFTHEME = "local-pdftheme";
    static readonly TIMEOUT_DBLCLICK = 190;
    static readonly TIMEOUT_SEARCH = 300;
    static readonly TIMEOUT_INPUT = 256;
    static readonly TIMEOUT_BLOCKLOAD = 300;
    static readonly TIMEOUT_TRANSITION = 150;
    static readonly HELP_PATH: {
        zh_CN: string;
        zh_CHT: string;
        zh_CN_Sillot: string;
        en_US: string;
        fr_FR: string;
    };
    static readonly QUICK_DECK_ID = "20230218211946-2kw8jgx";
    static readonly KEYCODE: {
        [key: string]: string[];
    };
    static readonly SIYUAN_KEYMAP: IKeymap;
    static readonly SIYUAN_EMPTY_LAYOUT: Record<string, unknown>;
    static readonly SIYUAN_IMAGE_VIP: string;
    static readonly SIYUAN_IMAGE_FILE: string;
    static readonly SIYUAN_IMAGE_NOTE: string;
    static readonly SIYUAN_IMAGE_FOLDER: string;
    static readonly SIYUAN_ASSETS_IMAGE: string[];
    static readonly SIYUAN_ASSETS_AUDIO: string[];
    static readonly SIYUAN_ASSETS_VIDEO: string[];
    static readonly SIYUAN_ASSETS_EXTS: string[];
    static readonly SIYUAN_CONFIG_APPEARANCE_DARK_CODE: string[];
    static readonly SIYUAN_CONFIG_APPEARANCE_LIGHT_CODE: string[];
    static readonly ZWSP: string;
    static readonly INLINE_TYPE: string[];
    static readonly BLOCK_HINT_KEYS: string[];
    static readonly BLOCK_HINT_CLOSE_KEYS: IObject;
    static readonly CODE_LANGUAGES: string[];
    static readonly ANALYTICS_EVT_ON_GET_CONFIG: string;
}
